# Generated by Django 3.2.9 on 2021-12-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Level', models.FloatField(blank=True, null=True)),
                ('Aeration', models.BooleanField(default=True)),
                ('Feed', models.BooleanField(default=True)),
                ('Mixer', models.BooleanField(default=True)),
                ('Overflow', models.BooleanField(default=True)),
                ('Recycle', models.BooleanField(default=True)),
                ('Substrate', models.BooleanField(default=True)),
                ('CO2', models.FloatField(blank=True, null=True)),
                ('Mixing', models.FloatField(blank=True, null=True)),
                ('pH', models.FloatField(blank=True, null=True)),
                ('Temperature', models.FloatField(blank=True, null=True)),
                ('Redox', models.FloatField(blank=True, null=True)),
                ('Turbidity', models.FloatField(blank=True, null=True)),
                ('Oxygen', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Created Time')),
            ],
            options={
                'db_table': 'Measurements',
                'managed': True,
            },
        ),
    ]
