# Generated by Django 3.2.9 on 2021-12-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='Flow',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
